[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
rust-version = "1.91"
repository = "https://github.com/kylekingcdn/libconf-rs"
license = "MIT"
publish = true

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
