[workspace]
resolver = "3"
members = [
    "crates/*",
    "examples/*/bin*",
    "examples/*/lib",
    "examples/readme",
]
exclude = [
    # FIXME: broken due to feature unification?
    "examples/2-serde-optional/bin-no-serde",
]

[workspace.package]
description = "Proc-macro providing library authors with first-class configuration for their end-users"
version = "0.2.3"
edition = "2024"
rust-version = "1.91"
repository = "https://github.com/kylekingcdn/lib-conf-rs"
license = "MIT"
publish = false

[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
config = { version = "0.15.25", default-features = false }
dotenvy = "0.15.7"
lib-conf = { version = "0.2.3", path = "crates/lib-conf" }
lib-conf-derive = { version = "0.2.3", path = "crates/lib-conf-derive" }
log = { version = "0.4.18", default-features = false }
prettyplease = "0.3.0"
proc-macro2 = "1.0.107"
quote = "1.0.47"
serde = "1.0.229"
secrecy = "0.10.3"
sqlx = { version = "0.8.6", default-features = false }
syn = "3.0.4"
thiserror = "2.0.20"
url = "2.5.8"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
bool_assert_comparison = "allow"
match_bool = "allow"
single_match_else = "allow"
