[package]
name = "example2-bin-no-serde"
description.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
example2-lib = { path = "../lib", package = "lib-conf-example2-lib" }
dotenvy = { workspace = true }
secrecy = { workspace = true }

[lints]
workspace = true
