[package]
name = "lib-conf-example2-lib"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
#publish = true # TODO: enable

[features]
default = []
serde = ["dep:serde", "lib-conf/serde"]

[dependencies]
lib-conf = { workspace = true }
serde = { workspace = true, optional = true, features = ["derive"] }

[lints]
workspace = true
