[package]
name = "libconf"
description = "Proc-macro providing library authors with first-class configuration for their end-users"
version = "0.0.1-pre1"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]

[lib]
proc-macro = true

[[example]]
name = "basic"
crate-type = ["lib"]

[[example]]
name = "library_consumer"
path = "examples/library_consumer/consumer_code.rs"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
