[package]
name = "lib-conf"
description = "Proc-macro providing library authors with first-class configuration for their end-users"
version = "0.0.1-pre1"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = true

[lints]
workspace = true

[features]
default = []
syn-debug = ["syn/extra-traits"]

[dependencies]
prettyplease = { version = "0.3.0" }
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = "3.0.4"
thiserror = "2.0.20"

[lib]
proc-macro = true

[dev-dependencies]
config = { version = "0.15.25", default-features = false }
dotenvy = "0.15.7"
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0.229", features = ["alloc", "derive"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
