[package]
name = "lib-conf"
description.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = true

[lints]
workspace = true

[features]
# feature groups
default = ["derive"]
standard = ["derive", "serde"]
# dep gates
derive = ["dep:lib-conf-derive"]
# passthrough flags
serde = ["lib-conf-derive?/serde"]
syn-debug = ["lib-conf-derive?/syn-debug"]

[dependencies]
lib-conf-derive = { workspace = true, optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
